### ISSUE TITLE
Decisions on basic UI component library

### ISSUE THREAD

**Issue by obstropolos** [tqtezos/minter#12]
Designate the component library used for the vanilla version

**Comment by alex-kooper** [comment]
I have been researching different React component libraries potentially useful for the project. The following have been considered:

- [Reakit](https://reakit.io) uses a very flexible approach by separating state management from view in every component
       **PROS** Very flexible look and feel, great composability
      **CONS** Components come without styles, small number of prebuilt  components

- [Chakra UI](https://chakra-ui.com) Style props are used as a way to alter the style of a component by simply passing props to it. It uses [Styled System](https://styled-system.com/) to implement this approach which  is based on [Emotion](https://emotion.sh/docs/introduction)
  **PROS** Components come already styled, it is very easy to restyle components as well as lay them out on the page
  **CONS** The variety of supported components is not as good as some other alternatives can offer

- [Material UI](https://material-ui.com/) One of the most popular React component library with built in CSS-IN-JS solution: [CSS-IN-JS solution](https://cssinjs.org)
  **PROS** A great number of prebuilt components, flexible way to restyle them, well supported and documented.
  **CONS** Somewhat heavy, [CSS-IN-JS](https://cssinjs.org)is not the best possible solution today

- [Ant Design](https://ant.design) One of the most popular React component libraries.
   **PROS** It has probably more prebuilt components than any other library, relatively well documented
   **CONS** It uses SASS for styling, it does not use CSS-IN-JS or any other modern styling solution

At this point I would recommend to use [Ant Design](https://ant.design) but add to it some modern styling solution like [Styled Component](https://styled-components.com/) or [Emotion](https://emotion.sh). I would probably go with [Emotion](https://emotion.sh).

**Comment by obstropolos** [comment]
Moved from snowpack to create-react-app, utilizing Ant. closing.
