### ISSUE TITLE
Create the means to refresh existing contracts in the stepper to ensure that originated collections come up as an option

### ISSUE THREAD

**Issue by obstropolos** [tqtezos/minter#155]
In the NFT creation stepper, when creating a new collection, sometimes it doesn't show up as an option to mint your tokens to even if the contract was successfully originated.

This likely has to do with indexing - we need to figure out a means to either refresh it, figure out how to gate a user with a modal until it shows up, or add a small refresh button.

**Comment by lambdahands** [comment]
There's no data-refetching implemented yet, so this is expected, which is why I changed the label to `enhancement`
