### ISSUE TITLE
Invalid Yarn subcommand on build release images

### ISSUE THREAD

**Issue by bitc0m** [tqtezos/minter#162]
Latest build 2cc92933aae94891c2a1ea1e538bc02a02bb12e0 on origin/master build release fails on Ubuntu 20.10 with Yarn 1.22.5 installed. Installing Typescript via Yarn fails as the install command was replaced with add in later releases.

```
~/minter/bin$ ./build-release-images 
Environment: dev-sandbox
Docker stack: minter-dev-sandbox
Project root dir: /home/sockzy/minter
Sending build context to Docker daemon  7.168kB
Step 1/4 : FROM bash:4.4.12
 ---> 2c3838775cf0
Step 2/4 : MAINTAINER Cosmin Titei
 ---> Using cache
 ---> 3c0fbc48e821
Step 3/4 : RUN apk add --no-cache curl
 ---> Using cache
 ---> 403e0504bc64
Step 4/4 : CMD ["bash"]
 ---> Using cache
 ---> 302418865162
Successfully built 302418865162
Successfully tagged bashcurl:latest
Sending build context to Docker daemon  3.068MB
Step 1/8 : FROM node:12
 ---> 9756a2cb8e53
Step 2/8 : WORKDIR /usr/src/app/server
 ---> Using cache
 ---> 248e45e0ffaf
Step 3/8 : COPY server .
 ---> Using cache
 ---> 63c12a914630
Step 4/8 : RUN yarn install
 ---> Using cache
 ---> b1f8b56177bd
Step 5/8 : RUN yarn global install typescript
 ---> Running in 360ee0923800
yarn global v1.22.5
error Invalid subcommand. Try "add, bin, dir, ls, list, remove, upgrade, upgrade-interactive"
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
The command '/bin/sh -c yarn global install typescript' returned a non-zero code: 1

```

**Comment by lambdahands** [comment]
Hi, thanks for this report. The release build setup is outdated, and the way we plan on deploying OpenMinter likely won't use the `bin/build-release-images` command. As of now, we don't officially support deploying to a production environment, but the building blocks to do so have been implemented.

A production release step would look something like:
- Configure OpenMinter via the `config/` directory
- Run a bootstrap script that reads the config, creates new contracts, and generates static client/server config files
- Build the client for production  (using `yarn build`)
- Host the static build output of the client
- Host a remote instance of the Node server

**Comment by lambdahands** [comment]
As of v0.4.0, release images are no longer required, and the application can be compiled as a static JS bundle.
