### ISSUE TITLE
Support for batch minting of NFTs

### ISSUE THREAD

**Issue by obstropolos** [tqtezos/minter#164]
**Updating requirements as of 5/10 for MVP of batch minting**

Core requirements: 
Enable users to fill in and upload a CSV template in order to batch mint. The template must include fields for basic metadata, and an IPFS column to indicate where the underlying artifact lives. This core version _will not_ have embedded support in the form but rather will require the user to pre-fill all information.

As a user:
- I can toggle `batch mint` on the new asset form
- I can download a CSV template to input my batch mint information
- I can re-upload that template, and pay the required costs to mint my indicated tokens (bypassing the original form steps) 

Open questions:
- Batch mint limitations

**Comment by paulo60pg** [comment]
Any chance to see this implemented in the next release ? Really a must have feature in my opinion.
