### ISSUE TITLE
Integrate Apollo as a GraphQL client

### ISSUE THREAD

**Issue by obstropolos** [tqtezos/minter#18]

**Comment by lambdahands** [comment]
Here are examples of mutations, subscriptions, and queries you can run in the GraphQL playground. We'll add these to the client, using [operation names](https://graphql.org/learn/queries/#operation-name) and [variables](https://graphql.org/learn/queries/#variables).

### Subscriptions

*Note: Run this in a separate playground tab and you'll see live updates!*

```graphql
subscription {
  operationConfirmed {
    hash
  }
}
```

### Mutations

```graphql
mutation {
  createNonFungibleToken(
    name: "New test token",
    description: "A test token",
    symbol: "TEST",
    ipfs_hash: "..." # ipfs_hash validation pending
  ) {
    id
    hash
    initiator
    method
    params
    status
  }
}
```

### Queries

```graphql
{
  nftByTokenId(token_id: "0") {
    token_id
    extras
    decimals
    symbol
    owner
  }
}
```

```graphql
{
  nfts {
    token_id
    extras
    decimals
    symbol
    owner
  }
}
```
