### ISSUE TITLE
Get rid of Config requirement (at least on testnet)

### ISSUE THREAD

**Issue by d4hines** [tqtezos/minter#181]
In spite of the issue #180 I just made, a super smooth testnet experience is really important (and if you make smooth enough, maybe you can discount the argument I made in #180 ). To that end, I think you should try to get instructions like "Create accounts with these providers and add their API keys to this JSON file". You want the user to go as long as possible before editing config files (compare VS Code to Emacs).

What about this as a solution: Launch the UI before originating, and then use the users wallet to originate. Same thing with Pinata - launch the UI before you have the keys, and then have a textbox where people can paste their pinata keys in to activate the minter. Of course people who know what they're doing will want a config file by which they can automate this process, but GUI's are really, really nice to have when you're trying something new (compare AWS to provisioning a VM yourself).

The otehr way to do it is "convention over configuration" - let people drop ready-made config files into obvious locations as I did in #178 . At least then I don't have to worry about the contents of the file, just its acquisition and placement, but it's still inferior to a wizard that guides me through the process.

**Comment by mycodecrafting** [comment]
Hey @d4hines, thanks for the feedback! With the release of v0.4.1 we have streamlined the whole onboarding experience. Getting running on testnet is now a very simple process and requires no custom config.
