### ISSUE TITLE
Possible issue around Thanos Wallet connection

### ISSUE THREAD

**Issue by d4hines** [tqtezos/minter#182]
There was a little bit of hurdle connecting the Thanos wallet - I think if you send the request to one network but connect thanos to another network you hit a dead spot in the UI.

I haven't tested to confirm this - maybe I'm mistaken and it doesn't happen.

**Comment by d4hines** [comment]
Some more Thanos weirdness - once I relaunched the docker containers today, I had to do a bunch of refreshes and attempts before I could get Thanos and the app to coordinate with each other. There is at least one (and I think several) state in the state machine somewhere that isn't valid.

**Comment by obstropolos** [comment]
Closing due to updates from recent releases.
