### ISSUE TITLE
Can't create new collection

### ISSUE THREAD

**Issue by d4hines** [tqtezos/minter#183]
I can't seem to create a new collection beyond the default "Minter" collection. 

Yesterday, I got caught in this loop in the UI:
![loop](https://user-images.githubusercontent.com/25231383/107787121-ad5d0b00-6d1c-11eb-95dd-8b83960d7dc1.gif)

Today, I tried again and there's no loop. I can go through the buttons and dispatch the commands to Thanos; however, after I get the "Collection created successfully" message or whatever, I still don't see it anywhere, even after refreshing the page.

**Comment by murbard** [comment]
Same issue. The first time I create a collection it brings up a prompt for the name. I fill it, after about ~15 seconds Thanos show up. I confirm, it says collection created but it doesn't show up. After that, if I try to create a collection it just says "collection created" immediately as above.
