### ISSUE TITLE
Fatal crash on Invalid hex string

### ISSUE THREAD

**Issue by d4hines** [tqtezos/minter#187]
The app completely crashed with an error about `Invalid hex string`. If I recall, my steps were something like this:
- Install Thanos
- Run OpenMinter, do some things
- Remove Thanos
- Install Thanos again
- Try connecting OpenMinter to Thanos. The error occured.
The solution was to get Thanos in a state where I had the opportunity "reset the connection", which fixed it.

Maybe it's a ghost issue and not reproducible, but thought you guys should know.

**Comment by obstropolos** [comment]
Closing issue here - I believe this was solved via later versions of Beacon.
