### ISSUE TITLE
consider factoring out implicit sender validation to the top level main entry point 

### ISSUE THREAD

**Issue by emishur** [tqtezos/minter#191]
https://github.com/tqtezos/minter/blob/9bd894ec8c7a5a5a45d166f6b0c6b49c3810ddc7/contracts/ligo/src/english_auction_tez.mligo#L164

Check also all other functions called from `english_auction_tez_main`

**Comment by EGuenz** [comment]
Closed by https://github.com/tqtezos/minter/commit/4490a239187cd8a8babee7f6d7cac6cf57d89337
