### ISSUE TITLE
Carbon savings vs. Ethereum in UI

### ISSUE THREAD

**Issue by jacobarluck** [tqtezos/minter#206]
Add a small signpost during the minting period about how much carbon has been saved vs. minting the equivalent NFT on Ethereum.

https://memoakten.medium.com/the-unreasonable-ecological-cost-of-cryptoart-2221d3eb2053

**Comment by obstropolos** [comment]
@jacobarluck - is there a static number we can put here that can be a placeholder on the creation modal?

**Comment by mycodecrafting** [comment]
they give average numbers here for 3 NFTs we can probably use as the base:  https://medium.com/tezos-weekly-spotlight/around-the-tezos-nft-ecosystem-mike-tyka-hic-et-nunc-clean-nfts-and-interpop-3b0802fe3284

**Comment by obstropolos** [comment]
Closing - merged with the recent `0.4.3` cut
