### ISSUE TITLE
POST http://localhost:3000/ipfs-image-with-thumbnail-upload 404 (Not Found)

### ISSUE THREAD

**Issue by kalouo** [tqtezos/minter#207]
Hello. 

Trying to play with OpenMinter locally. I signed up for a free Pinata account, and added the API key/secret to the configuration along with my public/private keys. I am successfully able to spin up `testnet` with `yarn start:testnet` and then connect with the Temple wallet. 

However, when I try to create an asset – Step 3 of 3 – I get `Error: IPFS upload failed`. 

Opening Chrome DevTools, the error traces back to: `POST http://localhost:3000/ipfs-image-with-thumbnail-upload 404 (Not Found)`

Am I missing anything with the IPFS/Pinata setup?

**Comment by kalouo** [comment]
Never mind. Realised I'm supposed to run this on `localhost:9000` not 3000.

**Comment by WizardsKnow** [comment]
Running into this same issue, exploring same fix
