### ISSUE TITLE
Page is incorrect state after successful purchase

### ISSUE THREAD

**Issue by ccarella** [tqtezos/minter#219]
After you successfully buy and nft the page you are on still says "For Sale" and the button "Buy Now".

Either the page should refresh or they should be redirected to the Collections page on success.

#121 
@mycodecrafting

**Comment by ccarella** [comment]
This is also true if you cancel an NFT sale. You wind up in a state where your NFT looks like its still available for sale.

**Comment by lambdahands** [comment]
Moved this discussion to #121
