### ISSUE TITLE
UX enhancement for users who have not connected a wallet and try to purchase an NFT

### ISSUE THREAD

**Issue by ccarella** [tqtezos/minter#220]
If a user arrives on an NFT for sale and has not connected their wallet and try to buy the NFT, it shows them checkout. When the user tries to checkout it displays an error. "Could not list token: no wallet connected"

When a user who has not connected their wallet lands on the site and tries to buy the NFT it should show them the Beacon connect wallet screen.

#121 
@mycodecrafting

**Comment by lambdahands** [comment]
Moved this discussion to #121
