### ISSUE TITLE
Non option to connect to the mainnet of Temple Wallet 

### ISSUE THREAD

**Issue by aleixfc** [tqtezos/minter#235]
Hi there,

Great project. I've found some issues though.

I've been testing the connection to several wallets via Beacon and I've found the following issues:
- Temple is the most intuitive one but, now somehow now I can not connect to the Wallet Mainnet. (Please see the image attached). I can't select the mainnet instead of the Edo2testnet.

<img width="416" alt="Screenshot 2021-03-11 at 00 30 32" src="https://user-images.githubusercontent.com/387553/110714825-691e3700-8204-11eb-98de-ddc2e5c431eb.png">

- Galleon: seems to work fine but when I try to connect it to Minter it throws an error "Beacon network mismatch"

- Kukai. I haven't found a way to get the secret key. So I can't add it to the config files.

Thank's in advance,

Aleix

**Comment by mycodecrafting** [comment]
Hey Aleix,

Minter should automatically select the correct network based on the Minter configuration. Is your minter installation set to run against mainnet or edo2net?

**Comment by aleixfc** [comment]
Hi mycodecrafting,

My minter installation was set to run against the mainnet. Although this issue has been solved with the last release.

Thanks,

Aleix
