### ISSUE TITLE
.mp4 metadata type is missing from minting page

### ISSUE THREAD

**Issue by jacobarluck** [tqtezos/minter#238]
<img width="573" alt="Screen Shot 2021-03-11 at 12 51 30 AM" src="https://user-images.githubusercontent.com/4146923/110742269-0f1d7180-8204-11eb-9951-a9e20524c561.png">

**Comment by maelswarm** [comment]
Why does the extension even matter? Shouldn't we be able to use ANY file? @mycodecrafting

**Comment by mycodecrafting** [comment]
Hey @maelswarm, it is true in theory an NFT asset can be *any* file, but the minter UI has to know how to render the asset. The ones given are the ones we fully support rendering. We are looking to add others such as 3D models (glb, gltf, obj, etc) and audio. If you have any types you would like to see supported, we welcome the suggestion

**Comment by maelswarm** [comment]
@mycodecrafting Understood

I was thinking https://github.com/sindresorhus/file-type + browserify could perhaps be leveraged.
