### ISSUE TITLE
10 NFT display limit per collection?

### ISSUE THREAD

**Issue by alon-eth** [tqtezos/minter#239]
Looks like only 10 NFTs load on the collections page with no ability to load more, and if going directly to the token detail page, only the last 10 NFTs in the collection load. If not one of the last 10, you get a "token not found" message.

**Comment by obstropolos** [comment]
This should be mitigated for now in the most recent build. 

However, we're working on buffing our indexing solution to prevent issues like this in the future. Closing this for now.
