### ISSUE TITLE
Mobile display is hard to use

### ISSUE THREAD

**Issue by murbard** [tqtezos/minter#244]
![Screenshot_20210314-124004](https://user-images.githubusercontent.com/1591742/111068901-85e79280-84c2-11eb-82d3-0a0e17c9f4dd.png)

Images are very small and captions are clipped.

**Comment by obstropolos** [comment]
Core mobile responsive issues handled via the `0.5.0` and `0.6.0` releases (marketplace, collections, asset page, new asset flow).
