### ISSUE TITLE
Failed to retrieve contract nfts from

### ISSUE THREAD

**Issue by kevinelliott** [tqtezos/minter#256]
Cloned the repo, ran `yarn install` then `yarn start` and this is what I get after connecting a wallet that has funds on Edonet.

<img width="624" alt="Screen Shot 2021-03-16 at 9 30 48 AM" src="https://user-images.githubusercontent.com/123112/111345358-71c6a100-863a-11eb-81e5-2a9e5a07b092.png">

Tried to create a Collection and an Item, but still get this error (so can't see Collection nor Item).

**Comment by mycodecrafting** [comment]
Hey! We just released v0.4.1 that should fix this issue. Please give it a try and let us know!

**Comment by kevinelliott** [comment]
@mycodecrafting That fixed it. Thanks for the quick fix.

**Comment by kevinelliott** [comment]
One issue that is lingering though, is upon creation of a Collection, it doesn't show up in Your Collections (i.e. no way to see the collection).

**Comment by kevinelliott** [comment]
^^ @mycodecrafting (just in case you didn't get notification because closed issue)

**Comment by kevinelliott** [comment]
Looks like another commit happened so I pulled again and now collections are working.

**Comment by kevinelliott** [comment]
Though now I have 5 of the same collection. Is there an easy way to burn empty collections?

**Comment by mycodecrafting** [comment]
Unfortunately, a collection is a contract, and there's no way to burn contracts AFAIK. The "owner" of the collection is based on who originated the contract. We could come up with some way to hide them in the UI though. Need to think through what that might look like and talk to others. If you like that idea, please open a feature request ticket for such a thing. Thanks!
