### ISSUE TITLE
pnpm > yarn + npm

### ISSUE THREAD

**Issue by maelswarm** [tqtezos/minter#258]
I've used this in past enterprise production environments. It's significantly faster on most occasions. Is migration worth it? Thoughts?

At a minimum yarn should be updated to 2.0?

[https://rushjs.io/pages/maintainer/package_managers/](https://rushjs.io/pages/maintainer/package_managers/)

**Comment by obstropolos** [comment]
We're going to stick to `yarn` for building OpenMinter. Closing this issue.
