### ISSUE TITLE
Collection list not being updated after a new collection is added

### ISSUE THREAD

**Issue by w4ll3** [tqtezos/minter#261]
Steps to reproduce:
- Create a new collection

Expected behavior: The new collection will be available for selection
Current behavior: The collection is created but you need to refresh the page to see it

**Comment by fmhc** [comment]
I experience the same issue, except that can not see any of the collections i successfully created. Is this related or the same?

Running Testnet Setting fresh install from Ubuntu 20.04 Subsystem on Windows 10, using the newest Chrome with Temple (Thanos) Wallet. I dont get any errors in the console, it just does not show any of my collections except the Featured "Minter" one, where i can successfully mint NFTs.

**Comment by w4ll3** [comment]
Not sure if they are related but at least for me I can see my collections, except that I must refresh the page in order the see it.

**Comment by fmhc** [comment]
which wallet / browser do you use?

**Comment by w4ll3** [comment]
I am currently on an Ubuntu 20.04 machine, using Temple wallet as well, with Version 89.0.4389.90 (Official Build) (64-bit) of Google Chrome

**Comment by maelswarm** [comment]
I ran into this today. Might be pertinent?
<img width="1920" alt="Capture" src="https://user-images.githubusercontent.com/6314185/111811884-8490de00-88a5-11eb-8202-ffdacb07c383.PNG">

**Comment by fmhc** [comment]
I checked out this PR and now i can see my collections https://github.com/tqtezos/minter/pull/260

But I experience the same behaviour that the collection list is not automatically updated when I add a new collection; i need to reload the page in the browser to see it.

**Comment by maelswarm** [comment]
<img width="1920" alt="aie846" src="https://user-images.githubusercontent.com/6314185/117343398-de576280-ae69-11eb-8dbd-dedd3792a4f6.PNG">

Upon attempting to create a new collection.

**Comment by obstropolos** [comment]
Since `0.7.0`, tzkt pulling new collections within 5 seconds of confirmation. Closing this now due to indexing changes.
