### ISSUE TITLE
Indexing Upgrades

### ISSUE THREAD

**Issue by jacobarluck** [tqtezos/minter#270]
link to tzcomet's token viewer to each individual asset page:

https://tqtezos.github.io/TZComet/staging/#/token/KT1RJ6PbjHpwc3M5rw5s2Nbmefwbuwbdxton/1143%3Fload-storage%3Dtrue%26go%3Dtrue%26explorer-input%3DKT1W4wh1qDc2g22DToaTfnCtALLJ7jHn38Xc

tzcomet will be moving to tzcomet.io soon so we can generate the links to that domain.

**Comment by obstropolos** [comment]
To note: 

All tz1 address links should go to tzkt 
To add: individual asset page should link out to Comet based on token ID.

**Comment by obstropolos** [comment]
Updating issue to reflect indexing upgrades, current work focused around tzkt implementation via #357

**Comment by obstropolos** [comment]
Handled via #357
