### ISSUE TITLE
Error: Failed to retrieve contract nfts from:

### ISSUE THREAD

**Issue by aleixfc** [tqtezos/minter#273]
Hi,

I've installed the last version (v0.4.2) and after link the wallet on mainnet I got this error.
I can not create collections either. "Error Creating Collection".

Thanks,

![image](https://user-images.githubusercontent.com/387553/111924283-fd5d8900-8aa3-11eb-8079-feff32346cf0.png)

**Comment by obstropolos** [comment]
Hey @aleixfc - 

Thanks for reporting. 

What's your current build setup, and have you tried running the latest build (`v0.4.3`)?

**Comment by aleixfc** [comment]
Hi @obstropolos 
Yes, V0.4.3 on Mac OS Movaje 10.14.6 is the build I ran. 
Please let me know if you need me to check other config files or system setup.

**Comment by obstropolos** [comment]
Yeah any additional context will be helpful here (we've also cut another beta version `v0.5.0` which includes a number of fixes). 

Were the contracts being retrieved from a version at or before the `v0.4.2` release - we've recently updated the contracts for assets. 

When you set up minter, was this a standard `yarn install` / `yarn start` run or was there a different setup you used.

**Comment by aleixfc** [comment]
Hi @obstropolos 
These are the steps I follow:
1. git clone https://github.com/tqtezos/minter.git 
2. then yarn install. I get these warning:
warning " > @typescript-eslint/eslint-plugin@4.13.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0 || ^7.0.0".
warning "@typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils@4.13.0" has unmet peer dependency "eslint@*".
warning " > @typescript-eslint/parser@4.13.0" has unmet peer dependency "eslint@^5.0.0 || ^6.0.0 || ^7.0.0".
warning "@emotion/styled > @emotion/babel-plugin@11.1.2" has unmet peer dependency "@babel/core@^7.0.0".
warning "@emotion/styled > @emotion/babel-plugin > @babel/plugin-syntax-jsx@7.12.1" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > react-redux@7.2.2" has unmet peer dependency "redux@^2.0.0 || ^3.0.0 || ^4.0.0-0".
warning " > @testing-library/user-event@7.1.2" has unmet peer dependency "@testing-library/dom@>=5".
warning " > @tsed/logger@5.5.2" has unmet peer dependency "source-map-support@^0.5.16".
warning "react-scripts > eslint-config-react-app@5.2.1" has incorrect peer dependency "@typescript-eslint/eslint-plugin@2.x".
warning "react-scripts > eslint-config-react-app@5.2.1" has incorrect peer dependency "@typescript-eslint/parser@2.x".

4. And yarn start. 

I don't know if it may help but firstly I installed version 0.2.1, then 0.4.2, 0.4.3, and finally this last version 0.5.1. With the 0.5.1 I get the same error.

**Comment by obstropolos** [comment]
Thanks for sharing this - we have someone on this issue immediately, hope to have it resolved shortly (additional rel #302)

**Comment by obstropolos** [comment]
Closing this - fixed via #345 and switching the Gateway to resolve using Pinata's gateway by default.
