### ISSUE TITLE
Bug: Collection from marketplace shows up in personal collections

### ISSUE THREAD

**Issue by obstropolos** [tqtezos/minter#294]
![Screen Shot 2021-03-26 at 4 10 15 PM](https://user-images.githubusercontent.com/18144858/112687439-e0330c80-8e4d-11eb-9003-eea80e000354.png)

Bug: When viewing an asset in the marketplace from someone's other collection, the collection shows up as an available option in your collections (even though you don't own any assets in it)

**Comment by maelswarm** [comment]
fix in -- #333
