### ISSUE TITLE
Display bugs in 0.5.0

### ISSUE THREAD

**Issue by jacobarluck** [tqtezos/minter#298]
"Cancel sale" is nearly obstructed from view

<img width="1719" alt="Screen Shot 2021-03-28 at 11 26 38 PM" src="https://user-images.githubusercontent.com/4146923/112783408-41f5a100-901d-11eb-9264-16ad2fcc94dd.png">

Full screen view doesn't fully encapsulate the artwork

<img width="1725" alt="Screen Shot 2021-03-28 at 11 39 19 PM" src="https://user-images.githubusercontent.com/4146923/112784137-df9da000-901e-11eb-9a60-ac00d49236f8.png">

**Comment by w4ll3** [comment]
Could you please share the screen resolution and image size so I can reproduce?

**Comment by obstropolos** [comment]
Fixed in #301
