### ISSUE TITLE
BUG: Card Resolution Scaling 

### ISSUE THREAD

**Issue by obstropolos** [tqtezos/minter#307]
Larger images shrunk and cut, smaller images sometimes get blown up and cut as well. Need to make sure the images conform to the card size either through reduction / framing. 

![Screen Shot 2021-03-31 at 1 41 02 PM](https://user-images.githubusercontent.com/18144858/113187369-c6ffd680-9226-11eb-9a4a-50bcc9443450.png)

**Comment by maelswarm** [comment]
#314
