### ISSUE TITLE
Marketplace page loading times are very slow

### ISSUE THREAD

**Issue by wyc** [tqtezos/minter#308]
For me, it takes up to 30 seconds before I can see any of the listings:

https://openminter.com/marketplace

Is it possible to speed this up without much development effort, such as by using a cache like Redis as many web applications do?

**Comment by maelswarm** [comment]
@wyc this may be apart of a larger conversation.

Lighthouse results on every page reveal that there's work to be done in general.

Service workers are also a must.

<img width="1920" alt="Capture" src="https://user-images.githubusercontent.com/6314185/113364963-7bc6f000-931a-11eb-8c89-be36e2d83dfd.PNG">

**Comment by obstropolos** [comment]
Update: faster load times being implemented via #357 due to indexing via tzkt

**Comment by obstropolos** [comment]
Handled via merging #357 - currently in `develop` - will be formally in release cut in `0.7.0`
