### ISSUE TITLE
Individual asset page cutting marketplace controls

### ISSUE THREAD

**Issue by obstropolos** [tqtezos/minter#322]
Currently, some images end up cutting off marketplace functionality due to resolution issues.

**Comment by obstropolos** [comment]
Example: 
<img width="826" alt="Screen Shot 2021-04-06 at 5 44 33 PM" src="https://user-images.githubusercontent.com/18144858/113782170-c328f400-96ff-11eb-902c-43133b511445.png">

**Comment by maelswarm** [comment]
A ```max-height``` against the ```height: 100%``` should fix this

**Comment by obstropolos** [comment]
Fixed via #337 and #345 release.
