### ISSUE TITLE
Add /network name to the BCD link

### ISSUE THREAD

**Issue by ungarson** [tqtezos/minter#335]
<img width="962" alt="Screenshot 2021-04-13 at 17 35 41" src="https://user-images.githubusercontent.com/13982759/114570680-b582e980-9c7e-11eb-8c84-189f2e8226a7.png">

This link refers to https://better-call.dev/KT1HriidwX43EYaZ7JDch7YuciXELhAn49Sd which is going to be redirected to https://better-call.dev/search?text=KT1HriidwX43EYaZ7JDch7YuciXELhAn49Sd, but in my thoughts the best solution would be to refer to `https://better-call.dev/*network_name*/KT1HriidwX43EYaZ7JDch7YuciXELhAn49Sd`, in my case it would've been https://better-call.dev/edo2net/KT1HriidwX43EYaZ7JDch7YuciXELhAn49Sd

**Comment by obstropolos** [comment]
Fixed via #409, will be merged and released with `0.7.1`
