### ISSUE TITLE
Some attributes can't be attached

### ISSUE THREAD

**Issue by ungarson** [tqtezos/minter#341]
Hi, I can't attach attribute `type` to an nft, it's always ignored. 
I guess it would be cool to see the list of ignored attributes on the page where I create nft.
Thanks.

**Comment by maelswarm** [comment]
#339

**Comment by ungarson** [comment]
@maelswarm ?

**Comment by maelswarm** [comment]
> @maelswarm ?

Hey

**Comment by ungarson** [comment]
@maelswarm is it relevant to the problem I've described? I just haven't found in common 🤔

**Comment by ungarson** [comment]
I'm going to close it, since no feedback was given 🤓
