### ISSUE TITLE
Show the name instead of the address

### ISSUE THREAD

**Issue by ungarson** [tqtezos/minter#349]
Hi, as you can see it shows me the address of a contract, which it couldn't derive NFTs from.
<img width="1440" alt="Screenshot 2021-04-20 at 19 06 07" src="https://user-images.githubusercontent.com/13982759/115428991-a1556400-a20b-11eb-9c8a-4c48f89ee23b.png">

My suggestion is that it should show the name instead of the address. It'd be more convenient.

**Comment by maelswarm** [comment]
@ungarson why?

**Comment by ungarson** [comment]
@maelswarm because I don't remember the addresses, I refer the contracts by their names... And so when I see this error I am trying to figure it out which is one of them is KT1HR....49Sd

**Comment by maelswarm** [comment]
@ungarson  but the selected collection is in the sidebar.

**Comment by ungarson** [comment]
@maelswarm nope, the selected collection seems to not have anything in common with the error. At least it's not necessary. I mean that there are 2 entities: the selected collection and the error, and they might not intersect.

**Comment by maelswarm** [comment]
@ungarson #358

**Comment by obstropolos** [comment]
Fix moved into `develop` by #358, will be included in the next release, closing for now. Thanks again.
