### ISSUE TITLE
Show 6 digits instead of 2

### ISSUE THREAD

**Issue by ungarson** [tqtezos/minter#350]
I've listed my token on sale for 0.001, but it shows that I've set it for 0.00 xtz

<img width="1044" alt="Screenshot 2021-04-21 at 15 12 44" src="https://user-images.githubusercontent.com/13982759/115551745-2ac07100-a2b4-11eb-998a-be2a50f10cc8.png">

I know that I'm going to pay for the fees more than I'd earn, but since it's possible to list token for less than 0.01, I guess it should be possible to see all the digits

**Comment by obstropolos** [comment]
Hey @ungarson - what version are you currently testing / building on?

**Comment by ungarson** [comment]
@obstropolos 0.2.0, that's what it says in the package-lock.json

**Comment by obstropolos** [comment]
This is fixed in recent releases - [check out](https://github.com/tqtezos/minter/releases/tag/v0.6.0) `0.5.0` and above:
<img width="757" alt="Screen Shot 2021-04-21 at 8 56 12 PM" src="https://user-images.githubusercontent.com/18144858/115640085-21e79380-a2e4-11eb-9277-63b0fc3c1ea8.png">

**Comment by ungarson** [comment]
@obstropolos thanks, could you please update the package.json file? It still says that the version is 0.2.0
