### ISSUE TITLE
Hide alerts

### ISSUE THREAD

**Issue by ungarson** [tqtezos/minter#351]
Hi, I was trying to cancel the sale, but it showed me an error, but the «‎Canceling sale»‎ alert is in progress anyway...

<img width="1044" alt="Screenshot 2021-04-21 at 15 19 11" src="https://user-images.githubusercontent.com/13982759/115552567-26488800-a2b5-11eb-8269-35c6bc12ea03.png">

What I'm trying to propose is that the alert should be closed, when an error occurs.

**Comment by obstropolos** [comment]
This is handled in recent releases through async modals: 
<img width="369" alt="Screen Shot 2021-04-21 at 9 03 00 PM" src="https://user-images.githubusercontent.com/18144858/115640457-fdd88200-a2e4-11eb-929e-74631c58cfa7.png">
