### ISSUE TITLE
List the token straight away

### ISSUE THREAD

**Issue by ungarson** [tqtezos/minter#352]
Hi, I'd like to know if it possible to add the «‎List»‎ button, so it would create the token and then list it, so I won't need to manually do it. I guess, it's the most common journey.

<img width="1000" alt="Screenshot 2021-04-21 at 15 30 11" src="https://user-images.githubusercontent.com/13982759/115553903-96a3d900-a2b6-11eb-8572-ced16a5ff71f.png">

**Comment by obstropolos** [comment]
Hey @ungarson - this is a great idea. 

We will consider adding it as part of the new asset flow as a toggle before creation, to create and list it in a number of ordered transactions.
