### ISSUE TITLE
Wrong alert

### ISSUE THREAD

**Issue by ungarson** [tqtezos/minter#353]
It showed me this alert, when I haven't done nothing but pressed on «‎List for sale»‎ button. That's a bug, I think.
<img width="1000" alt="Screenshot 2021-04-21 at 15 36 41" src="https://user-images.githubusercontent.com/13982759/115554750-7c1e2f80-a2b7-11eb-9637-6ca92d54de32.png">

**Comment by obstropolos** [comment]
This is solved via async notifications in a recent release `v0.6.0`
https://github.com/tqtezos/minter/releases/tag/v0.6.0
