### ISSUE TITLE
Add collection name (or its ID) to the URL

### ISSUE THREAD

**Issue by ungarson** [tqtezos/minter#354]
This way or some similar, I think:
<img width="987" alt="Screenshot 2021-04-21 at 15 38 55" src="https://user-images.githubusercontent.com/13982759/115555098-d28b6e00-a2b7-11eb-86f0-967bf9180ccc.png">

Why? Because right now it always loads this one:
<img width="987" alt="Screenshot 2021-04-21 at 15 40 12" src="https://user-images.githubusercontent.com/13982759/115555227-f0f16980-a2b7-11eb-96e5-fc44969f5557.png">

And so right now I need to wait before my browser loads this Minter, and only after it I can open up my other collection, which also takes time to load.

**Comment by obstropolos** [comment]
Hey @ungarson - it might get difficult with that kind of routing if two collections on an instance have the same exact name so the contract name serves as a unique reference.

**Comment by ungarson** [comment]
@obstropolos yes, that's why I've also mentioned some ID of the contract (contract address maybe)

**Comment by obstropolos** [comment]
To clarify would /collections/contract/name add a bit of context in this case?

**Comment by ungarson** [comment]
@obstropolos do you mean contract address by `contract` in the url? I might be wrong but I think one contract can't have multiple names if it belongs to one network, I think maybe `/collections/network/contract_address` would work fine
