### ISSUE TITLE
Add loader

### ISSUE THREAD

**Issue by ungarson** [tqtezos/minter#355]
It takes some time to load collection, and sometimes I'm confused where my collections have gone, so I guess the loader would be helpful
<img width="987" alt="Screenshot 2021-04-21 at 16 18 39" src="https://user-images.githubusercontent.com/13982759/115560569-63b11380-a2bd-11eb-8f39-9b58855f99ae.png">
<img width="987" alt="Screenshot 2021-04-21 at 16 18 57" src="https://user-images.githubusercontent.com/13982759/115560584-66136d80-a2bd-11eb-9ba9-3c3f3d278f3f.png">

**Comment by obstropolos** [comment]
Hey @ungarson - thanks for reporting this and suggesting this.
We're hoping to avoid the need to load specifically via a button with changes to indexing that will speed things up tremendously. Linked relevant development work for now via the issue.

**Comment by obstropolos** [comment]
tzkt merged in `0.7.0` with dramatic performance improvements - going to close this for now unless we continue to find problems in the future with fetching data.
