### ISSUE TITLE
Add feedback to the refresh button

### ISSUE THREAD

**Issue by ungarson** [tqtezos/minter#356]
It looks dead right now, I had to check the network tab if requests are really being sent. 
I think that some alert that would say «‎success»‎ would be good.
<img width="1195" alt="Screenshot 2021-04-21 at 21 28 37" src="https://user-images.githubusercontent.com/13982759/115603493-e13e4900-a2e8-11eb-8570-ba2696ae9662.png">

**Comment by obstropolos** [comment]
Refresh removed, tzkt indexing making things snappier. Merged into `develop`, will be included in `0.7.0`
