### ISSUE TITLE
Sell button should be disabled when it's already listing for sale

### ISSUE THREAD

**Issue by ungarson** [tqtezos/minter#361]
1. Open any asset
2. Press Sale 
3. Enter any amount
4. Confirm
5. And now it's pending but the "Sell" button in the asset page is still available to be pressed

**Comment by chiptus** [comment]
I guess that same thing for the buy button when buying an asset:
![Uploading image.png…]()

**Comment by chiptus** [comment]
and the sell button in the same page :)

**Comment by obstropolos** [comment]
Fixed with #424, will be added to `v0.7.1` release
