### ISSUE TITLE
Color of select collection dropdown

### ISSUE THREAD

**Issue by ungarson** [tqtezos/minter#363]
<img width="1440" alt="Screenshot 2021-04-22 at 14 19 47" src="https://user-images.githubusercontent.com/13982759/115706075-eb5a5900-a375-11eb-9a3e-172486ed89d5.png">

If I'm not mistaken, the same or similar color is used in Bootstrap to show disabled inputs, and since Bootstrap is kinda popular I got used to this, as well as probably a lot of other people 😀 My proposal is to change the color to more `able-friendly`: white maybe

**Comment by obstropolos** [comment]
Merged latest into develop, dropdown now white and will be cut with `0.7.0`
