### ISSUE TITLE
Pinata Cloud Error.

### ISSUE THREAD

**Issue by Blindripper** [tqtezos/minter#380]
OpenMinter Interface doesn't load. Brave Browser (Shield deactivated) console says: 

Failed to gateway.pinata.cloud/ipfs/QmWLVBkPX7kz6yM3h6bYG8qdrnsxqMv2AHXPayWvokzxcG/:1 load resource: net::ERR_FAILED.

![Screenshot-47](https://user-images.githubusercontent.com/39067706/115989025-788eef00-a5bc-11eb-9c47-8aa74bf3b2dd.png)

OpenMinter itself says:
Error Failed to retrieve contract nfts from: KT1QcxwB4QyPKfmSwjH1VRxa6kquUjeDWeEy

**Comment by obstropolos** [comment]
Hey @Blindripper let me know if you're still experiencing this in the latest release (`v0.7.0`)!

**Comment by Blindripper** [comment]
Works now. thx. Closed.
