### ISSUE TITLE
Ensure that the asset's creator is displayed properly on individual asset pages

### ISSUE THREAD

**Issue by obstropolos** [tqtezos/minter#407]
For some reason the `Minter:` on the individual asset page is showing up as a contract rather than the individual tz1/2/3 account that minted the token. 

<img width="600" alt="Screen Shot 2021-04-30 at 9 02 04 AM" src="https://user-images.githubusercontent.com/18144858/116698754-bd3ad180-a992-11eb-82dd-5e3ede49aa09.png">

**Comment by maelswarm** [comment]
@obstropolos @lambdahands 

Noticed this few days back and had something implemented with ```collection.creator```.
Pulled out because a refresh on the page wiped it (the set fallback to the tz account)

**Comment by obstropolos** [comment]
Fixed via #409, will be merged and released with `0.7.1`
