### ISSUE TITLE
Ensure tzkt is added to Sandbox configuration

### ISSUE THREAD

**Issue by obstropolos** [tqtezos/minter#416]
Need to implement a local version of tzkt to run with the sandbox version of OpenMinter due to our recent switch from BCD.

**Comment by chiptus** [comment]
I looked a bit into this. 

it seems like tzkt has an example docker-compose https://github.com/baking-bad/tzkt/blob/master/docker-compose.yml

I wonder if tzkt can share the same Postgres instance with BCD or just remove BCD from the configuration?
