### ISSUE TITLE
Support TZIP-16 metadata for FA2 contracts

### ISSUE THREAD

**Issue by emishur** [tqtezos/minter#7]

**Comment by obstropolos** [comment]
Goal for this is to have the asset creation contract support TZIP-16 metadata. 

Where it implements the TZIP12+16 basic metadata approach with a %token_metadata bigmap. 

see: https://gitlab.com/tzip/tzip/-/blob/0c8e9bbf12b0c006ff8114c8817a44473f536a75/proposals/tzip-12/tzip-12.md#token-metadata
